- name: Install current ssh public key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

#- name: Install github ssh keys for authorized users
#  command: "ssh-import-id-gh {{ item }}"
#  loop:
#    - stevemcquaid
#    - unp

- name: Set authorized key took from url
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  loop:
    - stevemcquaid
    - unp