- name: Install required system packages
  package:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-docker
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
  become: yes

- name: Install docker SDK for python3
  pip:
    name: docker
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes

- name: Install required system packages
  package:
    name: 
      - docker-ce
    state: latest
  become: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  become: yes

- name: Add ansible user user to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: 
      - docker
    append: yes
  become: yes

- name: Install python-pip package for use with docker ansible modules
  package:
    name:
    - python3-pip
    state: latest
    update_cache: yes
  become: yes
