- name: Add the user 'deploy'
  ansible.builtin.user:
    name: deploy
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  become: yes

- name: Set authorized key took from url
  authorized_key:
    user: deploy
    state: present
    key: "https://github.com/{{ item }}.keys"
  loop:
    - stevemcquaid
    - unp

- name: Allow the deploy user to run any commands as root with sudo -u root / sudo su -
  community.general.sudoers:
    name: deploy-sudo
    state: present
    user: deploy
    runas: root
    commands: ALL
  become: yes